import { HumanMessage, AIMessage, SystemMessage, ToolMessage } from "@langchain/core/messages";
import { graph } from "../graph/graph.js";
import { mongoDbService } from "../services/mongoDbService.js";
import { logger } from "../utils/logger.js";

/**
 * Reconstructs proper LangChain message instances from plain serialized JSON data.
 */
function reconstructMessages(serializedMessages) {
  if (!serializedMessages || !Array.isArray(serializedMessages)) return [];
  return serializedMessages.map((m) => {
    // If it's already an instance of a message, return it
    if (
      m instanceof HumanMessage ||
      m instanceof AIMessage ||
      m instanceof ToolMessage ||
      m instanceof SystemMessage
    ) {
      return m;
    }

    const fields = {
      content: m.content || "",
      name: m.name,
      additional_kwargs: m.additional_kwargs,
      response_metadata: m.response_metadata,
      id: m.id
    };

    switch (m.type) {
      case "human":
        return new HumanMessage(fields);
      case "ai":
        return new AIMessage({
          ...fields,
          tool_calls: m.tool_calls
        });
      case "tool":
        return new ToolMessage({
          ...fields,
          tool_call_id: m.tool_call_id
        });
      case "system":
        return new SystemMessage(fields);
      default:
        // Handle standard API formats or fallbacks
        if (m.role === "user") return new HumanMessage(fields);
        if (m.role === "assistant") return new AIMessage({ ...fields, tool_calls: m.tool_calls });
        if (m.role === "system") return new SystemMessage(fields);
        if (m.role === "tool") return new ToolMessage({ ...fields, tool_call_id: m.tool_call_id });
        return new HumanMessage(fields);
    }
  });
}

export const chatController = {
  /**
   * SSE Stream Handler for Chat responses.
   * POST /api/chat
   */
  async streamChat(req, res, next) {
    const { message, sessionId } = req.body;

    if (!message) {
      return res.status(400).json({ error: "Missing required 'message' in request body." });
    }

    const activeSessionId = sessionId || `session_${Date.now()}`;
    logger.info(`Starting chat stream for session: ${activeSessionId}`);

    // Set headers for Server-Sent Events (SSE)
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      "Connection": "keep-alive",
      "X-Accel-Buffering": "no" // Disable buffering for Nginx if present
    });

    let disconnected = false;

    res.on("close", () => {
      logger.info(`Client connection closed for session: ${activeSessionId}`);
      disconnected = true;
    });

    try {
      // 1. Load conversation state from persistence service
      const persistedState = await mongoDbService.loadState(activeSessionId) || {};

      // 2. Reconstruct messages to class instances
      const initialMessages = reconstructMessages(persistedState.messages || []);
      const initialBirthDetails = persistedState.userBirthDetails || {};
      const initialToolOutputs = persistedState.toolOutputs || [];
      const initialIntent = persistedState.currentIntent || "";

      // 3. Append the new user message
      const newHumanMsg = new HumanMessage({ content: message });
      const updatedMessages = [...initialMessages, newHumanMsg];

      const graphInput = {
        messages: [newHumanMsg], // passing the new message delta
        userBirthDetails: initialBirthDetails,
        toolOutputs: [],
        currentIntent: initialIntent
      };

      // 4. Stream events from LangGraph
      const eventStream = await graph.streamEvents(
        {
          messages: updatedMessages, // feed the full history to keep conversation state
          userBirthDetails: initialBirthDetails,
          toolOutputs: initialToolOutputs,
          currentIntent: initialIntent
        },
        {
          version: "v2",
          recursionLimit: 50 // Increase recursion limit to prevent GraphRecursionError
        }
      );

      // Keep local accumulators of graph updates to compute final state
      let messagesAcc = [...updatedMessages];
      let birthDetailsAcc = { ...initialBirthDetails };
      let toolOutputsAcc = [...initialToolOutputs];
      let intentAcc = initialIntent;

      for await (const event of eventStream) {
        if (disconnected) break;

        // Stream raw token content as it arrives from the model
        if (event.event === "on_chat_model_stream") {
          // Only stream tokens generated by the reasoningNode (astrology assistant)
          if (event.metadata?.langgraph_node === "reasoningNode") {
            const chunk = event.data?.chunk;
            if (chunk && chunk.content) {
              res.write(`data: ${JSON.stringify({ type: "token", content: chunk.content })}\n\n`);
            }
          }
        }
        // Emit tool execution notifications
        else if (event.event === "on_tool_start") {
          res.write(`data: ${JSON.stringify({
            type: "tool_start",
            tool: event.name,
            input: event.data?.input
          })}\n\n`);
        }
        else if (event.event === "on_tool_end") {
          res.write(`data: ${JSON.stringify({
            type: "tool_end",
            tool: event.name,
            output: event.data?.output
          })}\n\n`);
        }
        // Accumulate intermediate state updates returned from nodes
        else if (event.event === "on_node_end") {
          const output = event.data?.output;
          if (output) {
            if (output.messages) {
              const nodeMsgs = Array.isArray(output.messages) ? output.messages : [output.messages];
              messagesAcc = [...messagesAcc, ...reconstructMessages(nodeMsgs)];
            }
            if (output.userBirthDetails) {
              birthDetailsAcc = { ...birthDetailsAcc, ...output.userBirthDetails };
            }
            if (output.toolOutputs) {
              const nodeTools = Array.isArray(output.toolOutputs) ? output.toolOutputs : [output.toolOutputs];
              toolOutputsAcc = [...toolOutputsAcc, ...nodeTools];
            }
            if (output.currentIntent !== undefined) {
              intentAcc = output.currentIntent;
            }
          }
        }
      }

      if (!disconnected) {
        // Compile final state to save to MongoDB
        const finalState = {
          messages: messagesAcc,
          userBirthDetails: birthDetailsAcc,
          toolOutputs: toolOutputsAcc,
          currentIntent: intentAcc
        };

        await mongoDbService.saveState(activeSessionId, finalState);

        // Send done event with final payload
        res.write(`data: ${JSON.stringify({
          type: "done",
          sessionId: activeSessionId,
          state: finalState
        })}\n\n`);
        res.end();
      }

    } catch (error) {
      logger.error(`Error streaming chat for session ${activeSessionId}:`, error);
      if (!disconnected) {
        res.write(`data: ${JSON.stringify({ type: "error", message: error.message })}\n\n`);
        res.end();
      }
    }
  }
};
